### ISSUE TITLE
Error in the script path following

### ISSUE THREAD

**Issue by brehiner** [TheMaker-93/2020-Fun_Race_3d_SpeedTest#1]
Temporal
UnityEngine.Debug:LogError(Object)
PathFollowing:RotateToNextPoint() (at Assets/GAME/1_SCRIPTS/Player/PathFollowing.cs:74)
PathFollowing:MoveToNextPoint() (at Assets/GAME/1_SCRIPTS/Player/PathFollowing.cs:62)
PathFollowing:FixedUpdate() (at Assets/GAME/1_SCRIPTS/Player/PathFollowing.cs:47)

**Comment by TheMaker-93** [comment]
The path for the player to follow is defined on the Mono object called "LevelPathManager". If the list is empty then the list of waypoints for the player to follow will be too. The transform holding this object is on Scene/Level/LevelPath.

However, it should be working for the get go, It was tested prior to posting.

![image](https://user-images.githubusercontent.com/38749147/93767113-c8b56580-fc17-11ea-8002-7b31d8bf9d40.png)

Also, for this to work "LevelPathManager" must be referenced on the object "GameController". But, as told before, it should be referenced from the get go.

Have a nice Monday!

**Comment by TheMaker-93** [comment]
And yes, the [Element 0] should NOT be the transform of the host of the script. That's my mistake. :/ It should start with P0

**Comment by brehiner** [comment]
Everything is as you say but nevertheles the error keeps there. 

![error 1](https://user-images.githubusercontent.com/24891091/93770599-00a1b600-fbe2-11ea-9aed-9e705ad6574c.png)
![error 2](https://user-images.githubusercontent.com/24891091/93770609-05666a00-fbe2-11ea-8431-87c51df2aecd.png)

**Comment by TheMaker-93** [comment]
Ok, that is my fault. I do not see pretty well so I usually use the colour cues of the different Debug.log types in order to parse the information I want to be shown in the Console. It is not an error, it is just a Debug,LogError placed in a bad place. It will not happen again; I see how inappropriate it is and was placed this way instinctively.

It means that the rotation of the player is set in a very "prototype" way. it was set just a reminder for myself. If you update the project the "Temporal" message will be shown as a Debug.log and not as a LogError.

**Comment by TheMaker-93** [comment]
Don't worry, there are other bugs to find, I assure you.

**Comment by brehiner** [comment]
Thank you so much.....
Have a nice day!!!!

**Comment by TheMaker-93** [comment]
It is always a pleasure Brehiner. :)

You too have a nice day!!!
